export const AUTH_TYPES = {
  // Registration
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  
  // Login
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  
  // User management
  USER_LOADED: 'USER_LOADED',
  USER_LOADING: 'USER_LOADING',
  
  // Auth state
  AUTH_ERROR: 'AUTH_ERROR',
  LOGOUT: 'LOGOUT',
  CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
  
  // Token management
  TOKEN_REFRESH_REQUEST: 'TOKEN_REFRESH_REQUEST',
  TOKEN_REFRESH_SUCCESS: 'TOKEN_REFRESH_SUCCESS',
  TOKEN_REFRESH_FAIL: 'TOKEN_REFRESH_FAIL'
};

// For backward compatibility
export const REGISTER_SUCCESS = AUTH_TYPES.REGISTER_SUCCESS;
export const REGISTER_FAIL = AUTH_TYPES.REGISTER_FAIL;
export const LOGIN_SUCCESS = AUTH_TYPES.LOGIN_SUCCESS;
export const LOGIN_FAIL = AUTH_TYPES.LOGIN_FAIL;
export const USER_LOADED = AUTH_TYPES.USER_LOADED;
export const AUTH_ERROR = AUTH_TYPES.AUTH_ERROR;
export const LOGOUT = AUTH_TYPES.LOGOUT;