export const CHECKOUT_TYPES = {
  // Seat selection
  SET_SELECTED_SEATS: 'SET_SELECTED_SEATS',
  CLEAR_SELECTED_SEATS: 'CLEAR_SELECTED_SEATS',
  SET_SUGGESTED_SEATS: 'SET_SUGGESTED_SEATS',
  
  // Cinema and time selection
  SET_SELECTED_CINEMA: 'SET_SELECTED_CINEMA',
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',
  SET_SELECTED_TIME: 'SET_SELECTED_TIME',
  SET_SELECTED_MOVIE: 'SET_SELECTED_MOVIE',
  
  // UI state
  TOGGLE_LOGIN_POPUP: 'TOGGLE_LOGIN_POPUP',
  SET_LOGIN_POPUP: 'SET_LOGIN_POPUP',
  
  // Invitation system
  SHOW_INVITATION_FORM: 'SHOW_INVITATION_FORM',
  HIDE_INVITATION_FORM: 'HIDE_INVITATION_FORM',
  SET_INVITATION: 'SET_INVITATION',
  CLEAR_INVITATION: 'CLEAR_INVITATION',
  
  // QR Code
  SET_QR_CODE: 'SET_QR_CODE',
  CLEAR_QR_CODE: 'CLEAR_QR_CODE',
  
  // Checkout process
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  CHECKOUT_FAIL: 'CHECKOUT_FAIL',
  
  // Reset
  RESET_CHECKOUT: 'RESET_CHECKOUT',
  
  // Loading states
  SET_CHECKOUT_LOADING: 'SET_CHECKOUT_LOADING',
  
  // Error handling
  SET_CHECKOUT_ERROR: 'SET_CHECKOUT_ERROR',
  CLEAR_CHECKOUT_ERROR: 'CLEAR_CHECKOUT_ERROR'
};

// For backward compatibility
export const SET_SELECTED_SEATS = CHECKOUT_TYPES.SET_SELECTED_SEATS;
export const SET_SUGGESTED_SEATS = CHECKOUT_TYPES.SET_SUGGESTED_SEATS;
export const SET_SELECTED_CINEMA = CHECKOUT_TYPES.SET_SELECTED_CINEMA;
export const SET_SELECTED_DATE = CHECKOUT_TYPES.SET_SELECTED_DATE;
export const SET_SELECTED_TIME = CHECKOUT_TYPES.SET_SELECTED_TIME;
export const TOGGLE_LOGIN_POPUP = CHECKOUT_TYPES.TOGGLE_LOGIN_POPUP;
export const SHOW_INVITATION_FORM = CHECKOUT_TYPES.SHOW_INVITATION_FORM;
export const SET_INVITATION = CHECKOUT_TYPES.SET_INVITATION;
export const SET_QR_CODE = CHECKOUT_TYPES.SET_QR_CODE;
export const RESET_CHECKOUT = CHECKOUT_TYPES.RESET_CHECKOUT;

// client/src/store/types/cinemas.js
export const CINEMA_TYPES = {
  // Get all cinemas
  GET_CINEMAS_REQUEST: 'GET_CINEMAS_REQUEST',
  GET_CINEMAS_SUCCESS: 'GET_CINEMAS_SUCCESS',
  GET_CINEMAS_FAIL: 'GET_CINEMAS_FAIL',
  
  // Get single cinema
  GET_CINEMA_REQUEST: 'GET_CINEMA_REQUEST',
  GET_CINEMA_SUCCESS: 'GET_CINEMA_SUCCESS',
  GET_CINEMA_FAIL: 'GET_CINEMA_FAIL',
  
  // Select cinema
  SELECT_CINEMA: 'SELECT_CINEMA',
  CLEAR_SELECTED_CINEMA: 'CLEAR_SELECTED_CINEMA',
  
  // Create cinema (admin)
  CREATE_CINEMA_REQUEST: 'CREATE_CINEMA_REQUEST',
  CREATE_CINEMA_SUCCESS: 'CREATE_CINEMA_SUCCESS',
  CREATE_CINEMA_FAIL: 'CREATE_CINEMA_FAIL',
  
  // Update cinema (admin)
  UPDATE_CINEMA_REQUEST: 'UPDATE_CINEMA_REQUEST',
  UPDATE_CINEMA_SUCCESS: 'UPDATE_CINEMA_SUCCESS',
  UPDATE_CINEMA_FAIL: 'UPDATE_CINEMA_FAIL',
  
  // Delete cinema (admin)
  DELETE_CINEMA_REQUEST: 'DELETE_CINEMA_REQUEST',
  DELETE_CINEMA_SUCCESS: 'DELETE_CINEMA_SUCCESS',
  DELETE_CINEMA_FAIL: 'DELETE_CINEMA_FAIL',
  
  // Search and filter
  SEARCH_CINEMAS: 'SEARCH_CINEMAS',
  FILTER_CINEMAS: 'FILTER_CINEMAS',
  CLEAR_CINEMA_FILTERS: 'CLEAR_CINEMA_FILTERS',
  
  // Loading states
  SET_CINEMAS_LOADING: 'SET_CINEMAS_LOADING',
  
  // Error handling
  SET_CINEMA_ERROR: 'SET_CINEMA_ERROR',
  CLEAR_CINEMA_ERROR: 'CLEAR_CINEMA_ERROR'
};

// For backward compatibility
export const GET_CINEMAS = CINEMA_TYPES.GET_CINEMAS_SUCCESS;
export const GET_CINEMA = CINEMA_TYPES.GET_CINEMA_SUCCESS;
export const SELECT_CINEMA = CINEMA_TYPES.SELECT_CINEMA;
export const CREATE_CINEMA = CINEMA_TYPES.CREATE_CINEMA_SUCCESS;