export const GET_SHOWTIMES = 'GET_SHOWTIMES';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const SELECT_SHOWTIMES = 'SELECT_SHOWTIMES';
export const SELECT_ALL_SHOWTIMES = 'SELECT_ALL_SHOWTIMES';
export const DELETE_SHOWTIME = 'DELETE_SHOWTIME';
export const CLEAR_SELECTED_SHOWTIMES = 'CLEAR_SELECTED_SHOWTIMES';